import Head from "next/head";
import {Navigate} from "@/component/navigate/Navigate";
import {Welcome} from "@/sections/welcome/Welcome";
import {About} from "@/sections/about/about";
import {Contact} from "@/sections/contact/Contact";
import {Footer} from "@/component/footer/Footer";
import {Skills} from "@/sections/skills/Skills";
import {Projects} from "@/sections/projects/Projects";

export default function Home() {
    return (
        <>
            <Head>
                <title>Serge Developer</title>
                <meta name="description" content="Generated by create next app"/>
                <meta name="viewport" content="width=device-width, initial-scale=1"/>
                <link rel="icon" href="/favicon.png" />
            </Head>
            <main>
                <Navigate/>
                <Welcome/>
                <About/>
                <Skills/>
                <Projects />
                <Contact/>
                <Footer/>
            </main>
        </>
    );
}